# Generated by Django 5.1.1 on 2024-09-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.AddField(
            model_name='course',
            name='faculties',
            field=models.ManyToManyField(to='attendance.faculty'),
        ),
    ]
