# Generated by Django 5.1.1 on 2024-10-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_student_check_in_time_student_latitude_and_more'),
    ]

    operations = [
    ]
