# Generated by Django 5.1.1 on 2024-10-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_attendancestudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceStudent',
        ),
    ]
