# Generated by Django 5.1.1 on 2024-10-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='duration_hours',
        ),
    ]
