# Generated by Django 5.1.1 on 2024-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
