# Generated by Django 5.1.1 on 2024-10-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_alter_teacher_first_name_alter_teacher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
